### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Klatch13** [27rogi/Fabric2Discord#10]
https://mclo.gs/TpizJjd
I think it's because of your mod. Please check

**Comment by Klatch13** [comment]
@rogi27

**Comment by Klatch13** [comment]
Я же правильно понял что ты русский?

**Comment by 27rogi** [comment]
Попробуй новую версию 2.0.3 и отпишись касательно ошибки, инфы по ней маловато в официальном канале.

**Comment by Klatch13** [comment]
Вроде нету, но она у меня не сразу появилась. Так что если появится, то отпишу

**Comment by Klatch13** [comment]
```
[21:30:25] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'f2d'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.9.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:0.11.0]
Caused by: dev.kord.core.exception.EntityNotFoundException: Webhook with id 1003737993867165858 was not found.
	at dev.kord.core.supplier.EntitySupplier$DefaultImpls.getWebhook(EntitySupplier.kt:734) ~[dev_kord_kord-core-0.8.0-M16-9b31c6965733bfd0.jar:?]
	at dev.kord.core.supplier.EntitySupplier$getWebhook$1.invokeSuspend(EntitySupplier.kt) ~[dev_kord_kord-core-0.8.0-M16-9b31c6965733bfd0.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[org_jetbrains_kotlin_kotlin-stdlib-1.7.10-d8477032ea212bda.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) ~[f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) ~[f2d-2.0.3-beta+1.19.2.jar:?]
```

**Comment by Klatch13** [comment]
Я так понимаю я не так указал вебхук

**Comment by Klatch13** [comment]
Чтобы выли были уверены я вас уведомлю, что ошибок не было, вчера вечером запустил его и вот до утра ничего не происходило

**Comment by 27rogi** [comment]
Благодарю, думаю в таком случае можно закрыть проблему как решенную, если что произойдет - пишите.
