### ISSUE TITLE
Нет сообщений После ошибки

### ISSUE THREAD

**Issue by Klatch13** [27rogi/Fabric2Discord#14]
```
[17:16:48] [DefaultDispatcher-worker-15/ERROR]: Uncaught exception in thread "DefaultDispatcher-worker-15"
dev.kord.rest.request.KtorRequestException: REST request returned an error: 503 Service Unavailable  503: Service Unavailable null
	at dev.kord.rest.request.KtorRequestHandler.handle(KtorRequestHandler.kt:61) ~[f2d-2.0.3-beta+1.19.2.jar:?]
	at dev.kord.rest.request.KtorRequestHandler$handle$1.invokeSuspend(KtorRequestHandler.kt) ~[f2d-2.0.3-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [org_jetbrains_kotlin_kotlin-stdlib-1.7.10-5d3cb167aa9dc01b.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) [f2d-2.0.3-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [org_jetbrains_kotlin_kotlin-stdlib-1.7.10-5d3cb167aa9dc01b.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) [f2d-2.0.3-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [org_jetbrains_kotlin_kotlin-stdlib-1.7.10-5d3cb167aa9dc01b.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) [f2d-2.0.3-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [org_jetbrains_kotlin_kotlin-stdlib-1.7.10-5d3cb167aa9dc01b.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) [f2d-2.0.3-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [org_jetbrains_kotlin_kotlin-stdlib-1.7.10-5d3cb167aa9dc01b.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) [f2d-2.0.3-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [org_jetbrains_kotlin_kotlin-stdlib-1.7.10-5d3cb167aa9dc01b.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) [f2d-2.0.3-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) [f2d-2.0.3-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [org_jetbrains_kotlin_kotlin-stdlib-1.7.10-5d3cb167aa9dc01b.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-7443ef0125382611.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-7443ef0125382611.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-7443ef0125382611.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-7443ef0125382611.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-7443ef0125382611.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-7443ef0125382611.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-7443ef0125382611.jar:?]
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException
```
@rogi27

**Comment by Klatch13** [comment]
[2022-09-26-6.log](https://github.com/rogi27/Fabric2Discord/files/9651100/2022-09-26-6.log)
Лог если нужен

**Comment by Klatch13** [comment]
![image](https://user-images.githubusercontent.com/108920477/192421017-b51dff76-7a71-4bee-abd9-4f27663d59f3.png)
![image](https://user-images.githubusercontent.com/108920477/192421060-fa446284-3f97-4d70-97ae-ae1a8ac5a83a.png)
