### ISSUE TITLE
help please 😄 

### ISSUE THREAD

**Issue by Suhkur** [27rogi/Fabric2Discord#17]
[11:01:39] [Server thread/INFO]: Suhkur has made the advancement [Stone Age]
at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[11:01:57] [Server thread/ERROR]: Chain link failed, continuing to next one
java.lang.NoSuchMethodError: 'net.minecraft.class_2561 net.minecraft.class_7471.method_46291()'
	at space.ryzhenkov.fabric2discord.ktmixins.ServerPlayNetworkHandlerMixin.onPlayerMessageEvent(ServerPlayNetworkHandlerMixin.kt:15) ~[f2d-2.1.0+1.19.3.jar:?]
	at net.minecraft.class_3244.handler$zze000$onPlayerMessageEvent(class_3244.java:2519) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_44155(class_3244.java:1444) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_45064(class_3244.java:1302) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]

**Comment by 27rogi** [comment]
Strange, works on my side.
Could you provide a config file and which mods you are using?

**Comment by Suhkur** [comment]
I got it working, downgraded to 2.0.3.
