### ISSUE TITLE
Can't send chat messages in 1.19.2

### ISSUE THREAD

**Issue by ViniciusIth** [27rogi/Fabric2Discord#19]
In version `2.1.0+1.19.3` sending any non-command message in chat results in the following error.

```js
[12:57:30] [Server thread/ERROR]: Chain link failed, continuing to next one
java.lang.NoSuchMethodError: 'net.minecraft.class_2561 net.minecraft.class_7471.method_46291()'
	at space.ryzhenkov.fabric2discord.ktmixins.ServerPlayNetworkHandlerMixin.onPlayerMessageEvent(ServerPlayNetworkHandlerMixin.kt:15) ~[f2d-2.1.0+1.19.3.jar:?]
	at net.minecraft.class_3244.handler$zmh000$onPlayerMessageEvent(class_3244.java:6019) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_44155(class_3244.java:1444) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_45064(class_3244.java:1302) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zcm000$modifiedRunLoop(MinecraftServer.java:3894) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by 27rogi** [comment]
1.19.2 is no longer supported, sorry. Use 1.19.4 instead.
