### ISSUE TITLE
Failing start Quilt server

### ISSUE THREAD

**Issue by McKpol** [27rogi/Fabric2Discord#32]
[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'f2d'!
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66) ~[quilt-loader-0.19.2.jar:?]
        at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34) ~[quilt-loader-0.19.2.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64) ~[quilt-loader-0.19.2.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.19.2.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.19.2.jar:?]
        at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:65) ~[quilt-loader-0.19.2.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[transformed-mod-minecraft.i0:0/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.19.2.jar:?]
        at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.19.2.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) ~[quilt-loader-0.19.2.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:66) ~[quilt-loader-0.19.2.jar:?]
Caused by: dev.kord.core.exception.EntityNotFoundException: Webhook with id 0 was not found.
        at dev.kord.core.supplier.EntitySupplier$DefaultImpls.getWebhook(EntitySupplier.kt:767) ~[transformed-mod-f2d.i0:0/:?]
        at dev.kord.core.supplier.EntitySupplier$getWebhook$1.invokeSuspend(EntitySupplier.kt) ~[transformed-mod-f2d.i0:0/:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[transformed-mod-org-jetbrains-kotlin-kotlin-stdlib.i0:0/:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) ~[transformed-mod-org-jetbrains-kotlinx-kotlinx-coroutines-core-jvm.i0:0/:?]
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) ~[transformed-mod-org-jetbrains-kotlinx-kotlinx-coroutines-core-jvm.i0:0/:?]
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[transformed-mod-org-jetbrains-kotlinx-kotlinx-coroutines-core-jvm.i0:0/:?]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[transformed-mod-org-jetbrains-kotlinx-kotlinx-coroutines-core-jvm.i0:0/:?]
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[transformed-mod-org-jetbrains-kotlinx-kotlinx-coroutines-core-jvm.i0:0/:?]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[transformed-mod-org-jetbrains-kotlinx-kotlinx-coroutines-core-jvm.i0:0/:?]
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[transformed-mod-org-jetbrains-kotlinx-kotlinx-coroutines-core-jvm.i0:0/:?]
        at space.ryzhenkov.fabric2discord.F2D.onInitialize(F2D.kt:58) ~[transformed-mod-f2d.i0:0/:?]
        at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:65) ~[quilt-loader-0.19.2.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.19.2.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.19.2.jar:?]
        ... 16 more
        
I guess its because is the server is Quilt not Fabric

**Comment by McKpol** [comment]
I will just use other mod it work with Quilt Sever 👍
