### ISSUE TITLE
Connection refused: gateway.discord.gg/0.0.0.0:443

### ISSUE THREAD

**Issue by DefenderYAY** [27rogi/Fabric2Discord#6]
```
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155) ~[netty-transport-native-unix-common-4.1.77.Final.jar:?]
at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128) ~[netty-transport-native-unix-common-4.1.77.Final.jar:?]
at io.netty.channel.unix.Socket.finishConnect(Socket.java:321) ~[netty-transport-native-unix-common-4.1.77.Final.jar:?]
at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:477) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.77.Final.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
```
Issue is caused on a 1.19.1 Fabric Server.
Modset: 
![image](https://user-images.githubusercontent.com/107358273/183081327-8dd29c44-1677-4865-91df-0d6fa21376f9.png)
Config:
```
# Do not touch this value, it allows mod to check if config file is outdated or not.
configVersion=1
# Thanks for using Fabric2Discord!
# The configuration might look very complicated, so I made a simple WIKI to help you:
# https://github.com/rogi27/Fabric2Discord/wiki/Introduction
# 
# Since this plugin has a close bound with Placeholder API you might want to check it's WIKI:
# https://placeholders.pb4.eu/
general {
    # Here you specify ids for mod to work, setting value to 0 disables the feature
    ids {
        # Snowflake (id) of the channel used to link Discord and Minecraft messages
        # More on https://github.com/rogi27/Fabric2Discord/wiki/Getting-Started#basic-setup=
        chatChannel=dummy
        # Snowflake (id) of the channel used for join, leave, death and etc. messages
        # More on https://github.com/rogi27/Fabric2Discord/wiki/Getting-Started#basic-setup=
        logChannel=dummy
        # Snowflake (id) of the webhook used to send Minecraft messages using player data
        # More on https://github.com/rogi27/Fabric2Discord/wiki/Getting-Started#connecting-webhook=
        webhook=dummy
    }
    # Here you can enable custom bot statuses
    status {
        # Enables or disables this feature
        enabled=true
        # Status update interval in minutes (min = 1, max = 120)
        interval=1
        # Status type, variants: ONLINE, IDLE, DO_NOT_DISTURB, INVISIBLE, OFFLINE
        type="DO_NOT_DISTURB"
        # Status variants, chosen randomly.
        # Supports SERVER placeholders
        variants=[
            Fabric,
            "with %server:online% dudes",
            "in %world:name%"
        ]
    }
    # Your token should be here, check https://github.com/rogi27/Fabric2Discord/wiki/Getting-Started#connecting-webhook=
    token="bot_token(dummy token)"
}
```

**Comment by DefenderYAY** [comment]
Similar to: [Netty IP resolve crash #5](https://github.com/rogi27/Fabric2Discord/issues/5#issue-1328454117)

**Comment by 27rogi** [comment]
Do you have any firewall enabled?

**Comment by DefenderYAY** [comment]
> Do you have any firewall enabled?

No i'm hosting this on a third party website

**Comment by DefenderYAY** [comment]
Update: I tried using another chat integration mod(Fancy Discord), and it turns out that this issues occurs here as well. Could this be an issue with discord4j? 

![image](https://user-images.githubusercontent.com/107358273/183472767-b93de48f-2e01-403c-ab0a-e74c63bc90f4.png)

**Comment by 27rogi** [comment]
Hi, I changed Discord library from D4J to kord, could you download latest 2.0.0 beta and check if it works for you?
