### ISSUE TITLE
ForkJoinPool errors

### ISSUE THREAD

**Issue by gumdum** [27rogi/Fabric2Discord#7]
F2D chat is not working. I get these errors in my latest.log:

[19:56:07] [ForkJoinPool-1-worker-10/WARN]: Mod io_netty_netty-resolver-dns uses the version 4.1.77.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version

main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'f2d'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]

etc...

**Comment by 27rogi** [comment]
Thanks for reporting, might be somehow related to #5

**Comment by 27rogi** [comment]
Hi, I changed Discord library from D4J to kord, could you download latest 2.0.0 beta and check if it works for you?

**Comment by gumdum** [comment]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'f2d'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.9.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [minecraft_server-1.19.2.jar:0.11.0]
Caused by: dev.kord.rest.request.KtorRequestException: REST request returned an error: 403 Forbidden  Missing Permissions null
	at dev.kord.rest.request.KtorRequestHandler.handle(KtorRequestHandler.kt:61) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at dev.kord.rest.request.KtorRequestHandler$handle$1.invokeSuspend(KtorRequestHandler.kt) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[org_jetbrains_kotlin_kotlin-stdlib-1.7.10-d8477032ea212bda.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[org_jetbrains_kotlin_kotlin-stdlib-1.7.10-d8477032ea212bda.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[org_jetbrains_kotlin_kotlin-stdlib-1.7.10-d8477032ea212bda.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[org_jetbrains_kotlin_kotlin-stdlib-1.7.10-d8477032ea212bda.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[org_jetbrains_kotlin_kotlin-stdlib-1.7.10-d8477032ea212bda.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[org_jetbrains_kotlin_kotlin-stdlib-1.7.10-d8477032ea212bda.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[org_jetbrains_kotlin_kotlin-stdlib-1.7.10-d8477032ea212bda.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.4-df36bc3a2835acb7.jar:?]
	at space.ryzhenkov.fabric2discord.F2D.onInitialize(F2D.kt:32) ~[f2d-2.0.1-beta+1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
	... 8 more

**Comment by 27rogi** [comment]
Check if your bot has permissions to create messages, webhooks and etc.
Also be sure to enable switches as shown on the screenshot
![image](https://user-images.githubusercontent.com/10144091/184686128-a9c0094d-4a7b-44ce-ae8e-18db9156ed9a.png)
